### ISSUE TITLE
Create a RELEASE docker build

### ISSUE THREAD

**Issue by CDaRip2U** [odpi/egeria-connector-sas-viya#31]
Update the release build to add the docker export pieces to create release docker image.

**Comment by planetf1** [comment]
It appears there already is one. I'd forgotten I'd added originally to the <merge> build.

Of course this isn't ideal as the image is actually created first after the branch, and then may be updated as any last minute changes are added, but we currently have the same on egeria. It's a hang-over from before we switched to github actions on egeria. Now there are more choices.

Can move across to release if you wish. It's just a few conditional changes and cut/paste.

**Comment by planetf1** [comment]
To adopt this pattern, refer to egeria-database-connectors where the build scripts were refactored to do the docker image as part of the release process.
